DROP TABLE IF EXISTS credit_score;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS user_roles;
DROP TABLE IF EXISTS "user";
DROP TABLE IF EXISTS "role";

CREATE TABLE "user" (
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(25)   UNIQUE NOT NULL,
    email    VARCHAR(25)   UNIQUE NOT NULL,
    password VARCHAR(255)         NOT NULL
);

CREATE TABLE "role" (
    id        INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_name varchar(25) UNIQUE NOT NULL
);

CREATE TABLE user_roles (
    user_id INT NOT NULL,
    role_id INT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user"("id"),
    FOREIGN KEY (role_id) REFERENCES "role"("id")
);

CREATE TABLE customer (
    id       VARCHAR(11) PRIMARY KEY,
    name     VARCHAR(50) NOT NULL,
    surname  VARCHAR(25) NOT NULL,
    monthly_income FLOAT NOT NULL,
    email    VARCHAR(50) UNIQUE NOT NULL,
    phone    VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE credit_score (
    customer_id VARCHAR(11) NOT NULL,
    score       FLOAT       NOT NULL
);

INSERT INTO "user" (username, email, password)
VALUES ('admin', 'admin@creditsystem.com', '$2a$12$bsLxB.eRpvwK9tpskwVKLeY48sWKt1YxQnh8ZQLm0/rLUhtu0cAyK'); -- Aa123456!

INSERT INTO "role" (role_name)
VALUES ('ROLE_ADMIN'),
       ('ROLE_USER');

INSERT INTO user_roles (user_id, role_id)
VALUES (1, 1);

INSERT INTO credit_score(customer_id, score)
VALUES ('11111111111', 100),
       ('22222222222', 200),
       ('33333333333', 300),
       ('44444444444', 400),
       ('55555555555', 500),
       ('66666666666', 600),
       ('77777777777', 700),
       ('88888888888', 800),
       ('99999999999', 900),
       ('10101010101', 1000),
       ('11011011011', 1100),
       ('13131313131', 3200),
       ('14141414141', 2400);