DROP TABLE IF EXISTS credit_score;
DROP TABLE IF EXISTS customer;
DROP TABLE IF EXISTS "user";

CREATE TABLE "user" (
    id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(25)   UNIQUE NOT NULL,
    email    VARCHAR(25)   UNIQUE NOT NULL,
    password VARCHAR(255)         NOT NULL
);

CREATE TABLE customer (
    id       VARCHAR(11) PRIMARY KEY,
    name     VARCHAR(50) NOT NULL,
    surname  VARCHAR(25) NOT NULL,
    monthly_income FLOAT NOT NULL,
    email    VARCHAR(50) UNIQUE NOT NULL,
    phone    VARCHAR(25) UNIQUE NOT NULL
);

CREATE TABLE credit_score (
    customer_id VARCHAR(11) NOT NULL,
    score       FLOAT       NOT NULL
);

INSERT INTO credit_score(customer_id, score)
VALUES ('11111111111', 100),
       ('22222222222', 200),
       ('33333333333', 300),
       ('44444444444', 400),
       ('55555555555', 500),
       ('66666666666', 600),
       ('77777777777', 700),
       ('88888888888', 800),
       ('99999999999', 900),
       ('10101010101', 1000),
       ('11011011011', 1100),
       ('13131313131', 3200),
       ('14141414141', 2400);
